# framework:
#     rate_limiter:
#         # define 2 rate limiters (one for username+IP, the other for IP)
#         username_ip_login:
#             policy: token_bucket
#             limit: 3
#             rate: { interval: '1 minutes' }

#         ip_login:
#             policy: sliding_window
#             limit: 50
#             interval: '15 minutes'
            
security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users:
            entity:
                class: App\Entity\Account
                property: email
    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            login_throttling:
                max_attempts: 5
                interval: '15 minutes'
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # configure the maximum login attempts in a custom period of time
        # login_throttling:
        #     max_attempts: 2
        #     interval: '15 minutes'
  
        api:
            pattern:   ^/api
            stateless: true
            jwt: ~
            

        api_token_refresh:
            pattern: ^/api/token/refresh
            stateless: true
            refresh_jwt: ~

        # role_hierarchy:
        #     ROLE_USER:  ROLE_USER
        #     ROLE_ADMIN: [ROLE_USER, ROLE_ADMIN] # ROLE_SUPER_ADMIN a le rôle ROLE_ADMIN et le rôle ROLE_USER


    # access_control:

    # #Tous les utilisateurs on un account peuvent login
    #     - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    # #il faut être authentifié pour creer des accounts, ajouter un accounts, accounts
    #     - { path: ^/api/accounts, roles: ROLE_ADMIN, methods: [ PUT, PATCH, DELETE]}

    # #On n'a pas besoin de s'authentifier pour refresh le token.
    #     - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }